name: corsac_jwt
version: 0.5.0
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.0
  crypto: ^3.0.1
  logging: ^1.0.1
  pointycastle: ^3.0.1
  rsa_pkcs: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  # test_coverage:
    # git: https://github.com/priezz/test-coverage
